#! /usr/bin/env bash

ZNCDATA="/znc-data"

# Create znc config if it doesn't exist
if [ ! -f "${ZNCDATA}/configs/znc.conf" ]; then
  mkdir -p "${ZNCDATA}/configs"
  cp /src/znc.conf.default "${ZNCDATA}/configs/znc.conf"
fi

if [ ! -f "${ZNCDATA}/znc.pem" ]; then
  znc --makepem -d "$ZNCDATA"
fi

chown -R znc:znc $ZNCDATA
exec sudo -u znc znc -f -d "$ZNCDATA"
